# Generated by Django 4.2.4 on 2023-08-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_adset_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_adset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.adset')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.campaign')),
            ],
        ),
    ]
