# Generated by Django 4.2.4 on 2023-08-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_campaign_adset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='ad_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='data.adset'),
        ),
    ]
