# Generated by Django 4.2.4 on 2023-08-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_creative_ad_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign_adset',
        ),
    ]
